<?php
return ['x-generator'=>'GlotPress/4.0.1','translation-revision-date'=>'2022-10-13 16:54:29+0000','plural-forms'=>'nplurals=2; plural=n != 1;','project-id-version'=>'Plugins - List category posts - Stable (latest release)','language'=>'it','messages'=>['Include posts (id\'s)'=>'Includi articoli (id)','ID'=>'ID','Yes'=>'Sì','No'=>'No','Tags as class'=>'Tag come classe','Pagination'=>'Paginazione','These are general default options for List Category Posts. The idea in general will be that you can override them using the corresponding parameters in your shortcodes.'=>'Queste sono le opzioni predefinite per List Category Posts. In linea generale possono essere ridefinite utilizzando i parametri corrispondenti negli shortcode.','http://fernandobriano.com'=>'http://fernandobriano.com','Fernando Briano'=>'Fernando Briano','List Category Posts allows you to list posts by category in a post/page using the [catlist] shortcode. This shortcode accepts a category name or id, the order in which you want the posts to display, the number of posts to display and many more parameters. You can use [catlist] as many times as needed with different arguments. Usage: [catlist argument1=value1 argument2=value2].'=>'List Category Posts consente di generare una lista di articoli per categoria in un articolo/pagina utilizzando lo shortcode [catlist]. Questo shortcode accetta il nome o l\'id di una categoria, l\'ordine in cui si vuole che gli articoli siano mostrati, il numero di articoli da mostrare e molto altri parametri. Puoi utilizzare [catlist] tutte le volte che serve con argomenti differenti. Utilizzo: [catlist argomento1=valore1 argomento2=valore2].','https://github.com/picandocodigo/List-Category-Posts'=>'https://github.com/picandocodigo/List-Category-Posts','List category posts'=>'List category posts','Fork on Github'=>'Fork su Github','Donate'=>'Dona ','How to use'=>'Come usare','List Category Posts'=>'Lista articoli per categoria','List posts from a specified category'=>'Lista degli articoli da una categoria definita','Template'=>'Template','More link'=>'Altri link','Excerpt size'=>'Dimensioni riassunto','Excerpt'=>'Riassunto','Link to category (use \'catlink\' on the title field if you want the title of this widget to be a link to the category)'=>'Link alla categoria (usa \'catlink\' nel campo del titolo se vuoi che il titolo di questo widget sia un link alla categoria)','Thumbnail - size'=>'Miniatura - dimensioni','Show'=>'Visualizza','Exclude posts (id\'s)'=>'Escludi articoli (id)','Exclude categories (id\'s)'=>'Escludi categorie (id)','Ascending'=>'Crescente','Descending'=>'Decrescente','Order'=>'Ordine','Random'=>'Casuale','Author'=>'Autore','Post title'=>'Titolo dell\'articolo','Modified Date'=>'Data di modifica','Date'=>'Data','Order by'=>'Ordina per','Offset'=>'Offset','Number of posts'=>'Numero di articoli','Category'=>'Categoria','Title'=>'Titolo','If you\'ve found the plugin useful, consider making
      a <a href=\'http://picandocodigo.net/programacion/wordpress/list-category-posts-wordpress-plugin-english/\'
      title=\'Donate via PayPal\' rel=\'nofollow\'>donation via PayPal</a>
      or visit my Amazon Wishlist
      for <a href=\'http://www.amazon.com/gp/registry/wishlist/2HU1JYOF7DX5Q/ref=wl_web\'
      title=\'Amazon Wishlist\' rel=\'nofollow\'>books</a>
      or <a href=\'http://www.amazon.com/registry/wishlist/1LVYAOJAZQOI0/ref=cm_wl_rlist_go_o\'
      rel=\'nofollow\'>comic books</a> :).'=>'Se hai trovato utile il plugin, considera la possibilità di fare
      una <a href=\'http: //picandocodigo.net/programacion/wordpress/list-category-posts-wordpress-plugin-english/\'
      title=\'Dona tramite PayPal\' rel =\'nofollow\'>donazione con PayPal</a> o visita la mia lista desideri di Amazon per <a href=\'http://www.amazon.com/gp/registry/wishlist/2HU1JYOF7DX5Q/ref=wl_web\' title=\'Amazon Wishlist\' rel=\'nofollow\'>libri</a> o <a href=\'http://www.amazon.com/registry/wishlist/1LVYAOJAZQOI0/ref=cm_wl_rlist_go_o\' rel=\'nofollow\'>fumetti</a> :).','Please post <strong>new feature requests, Bug fixes,
      enhancements</strong>
      to <a href=\'https://github.com/picandocodigo/List-Category-Posts/issues\'>GitHub
      Issues</a> and check out the
      the <a href=\'https://github.com/picandocodigo/List-Category-Posts\'>GitHub
      repo</a> if you want to contribute code.'=>'Pubblica <strong>nuove richieste di funzionalità, correzioni di bug, 
      miglioramenti</strong> 
      su <a href=\'https://github.com/picandocodigo/List-Category-Posts/issues\'>GitHub
      Issues</a> e controlla il <a href=\'https://github.com/picandocodigo/List-Category-Posts\'>repository
      GitHub</a> se vuoi contribuire con il codice.','If you need help with the plugin, please visit
      the <a href=\'http://wordpress.org/support/plugin/list-category-posts\'>WordPress
      support forum</a>. Make sure
      you <a href=\'http://wordpress.org/extend/plugins/list-category-posts/other_notes/\'>read
      the instructions</a> to be aware of all the things you can do
      with List Category Posts and <a href=\'https://github.com/picandocodigo/List-Category-Posts/blob/master/doc/FAQ.md#frequently-asked-questions\'>check out the FAQ</a>.'=>'Se ti serve aiuto per questo plugin, visita
      il <a href=\'http://wordpress.org/support/plugin/list-category-posts\'>forum
      di supporto WordPress</a>. Assicurati di
      <a href=\'http://wordpress.org/extend/plugins/list-category-posts/other_notes/\'>leggere
      le istruzioni</a> per sapere tutto quello che puoi fare con List Category
      Posts e <a href=\'https://github.com/picandocodigo/List-Category-Posts/blob/master/doc/FAQ.md#frequently-asked-questions\'>dai un\'occhiata alle FAQ</a>.','Thanks for using List Category Posts.'=>'Grazie per utilizzare List Category Posts.','-1 - displays ALL THE POSTS (no limit)'=>'-1 - mostra TUTTI GLI ARTICOLI (senza limiti)','0 - displays the max number of posts per page'=>'0 - mostra il numero massimo di articoli per pagina','Default number of posts (overriden using <code>numberposts</code> parameter on each shortcode).'=>'Numero predefinito di articoli (sovrascritto usando il parametro <code>numberposts</code> in ogni shortcode).','Number of Posts'=>'Numero di articoli','You do not have sufficient permissions to access this page.'=>'Non si dispone di autorizzazioni sufficienti per accedere a questa pagina.','Continue reading &rarr;'=>'Continua la lettura &rarr;','Empty Term.'=>'Termine vuoto.']];